# Generated by Django 5.2.7 on 2025-10-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('seafood', 'Рыба и морепродукты'), ('meat', 'Мясо'), ('grains', 'Зерновые'), ('bee_products', 'Продукты пчеловодства'), ('nuts', 'Орехи и бобовые'), ('milk', 'Молочные продукты')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Аллерген',
                'verbose_name_plural': 'Аллергены',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рецепта, например: Овсянка с ягодами', max_length=150, verbose_name='Название блюда')),
                ('image', models.ImageField(blank=True, upload_to='dishes/', verbose_name='Фото блюда')),
                ('diet_type', models.CharField(blank=True, choices=[('classic', 'Классическое'), ('low_carb', 'Низкоуглеводное'), ('vegetarian', 'Вегетарианское'), ('keto', 'Кето')], max_length=50, null=True, verbose_name='Тип меню')),
                ('dish_type', models.CharField(blank=True, choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('dessert', 'Десерт')], max_length=50, null=True, verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Курица', max_length=100, unique=True, verbose_name='Название продукта')),
                ('description', models.TextField(blank=True, help_text='Краткое описание продукта или способа приготовления', verbose_name='Описание')),
                ('allergen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='foodplan_site.allergen', verbose_name='Аллерген')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Сколько нужно этого продукта', max_digits=10, verbose_name='Количество продукта')),
                ('unit', models.CharField(choices=[('g', 'г'), ('ml', 'мл'), ('pcs', 'шт.')], help_text='Единица измерения ингредиента', max_length=50, verbose_name='Единица измерения')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_recipes', to='foodplan_site.ingredient', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='foodplan_site.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецепта',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
