# Generated by Django 5.2.7 on 2025-10-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='dishes/', verbose_name='Фото блюда'),
        ),
    ]
