# Generated by Django 5.2.7 on 2025-10-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan_site', '0005_remove_ingredient_description_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Фото блюда'),
        ),
    ]
